// <auto-generated />
using System;
using Cvjećarnica_Zvončica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cvjećarnica_Zvončica.Migrations
{
    [DbContext(typeof(CvjecarnicaDbContext))]
    partial class CvjecarnicaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cvjećarnica_Zvončica.Models.Buket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buket");
                });

            modelBuilder.Entity("Cvjećarnica_Zvončica.Models.Cvijet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Boja")
                        .HasColumnType("int");

                    b.Property<int?>("BuketId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Naziv")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuketId");

                    b.ToTable("Cvijet");
                });

            modelBuilder.Entity("Cvjećarnica_Zvončica.Models.Cvijet", b =>
                {
                    b.HasOne("Cvjećarnica_Zvončica.Models.Buket", null)
                        .WithMany("Cvijece")
                        .HasForeignKey("BuketId");
                });

            modelBuilder.Entity("Cvjećarnica_Zvončica.Models.Buket", b =>
                {
                    b.Navigation("Cvijece");
                });
#pragma warning restore 612, 618
        }
    }
}
